version: 2
jobs:
    build:
        docker:
            - image: circleci/node:lts
        steps:
            - checkout
            - run: test docs/index.html
workflows:
    version: 2
    build:
        jobs:
            - build
